const {register ,getAnimal,getuserbyphone,verifCode, showalluser,activateAccount,login,forgetPassword,resetPassword,updatePassword,deleteAccount,getUser,updateProfile,addanim,editeanimal,removeanimal} = require ("../functions/User");
const express = require('express');
const { upload } = require("../utils/multerConfig");
const router = express.Router();
router.post('/register', register);
router.patch('/activateAccount/', activateAccount);
router.post('/login', login);
router.patch('/forgetPassword', forgetPassword);
router.patch('/resetPassword', resetPassword);
router.patch('/updatePassword', updatePassword);
router.delete('/deleteAccount', deleteAccount);
router.get('/getUser/:id', getUser);
router.get('/getUsers', showalluser);
router.patch('/updateProfile', upload.single('image'), updateProfile);
router.post('/addanim',addanim);
router.patch('/editeanimal',editeanimal);
router.delete('/removeanimal',removeanimal);
router.get('/verifCode',verifCode);
router.get('/getuserbyphone',getuserbyphone);
router.get('/getAnimal/',getAnimal);
module.exports = router;