const {register, activateAccount,login,forgetPassword,resetPassword,updatePassword,deleteAccount,getUser,updateProfile,addanim,editeanimal,removeanimal} = require ("../functions/User");
const express = require('express');
const router = express.Router();
router.post('/register', register);
router.patch('/activateAccount/', activateAccount);
router.post('/login', login);
router.patch('/forgetPassword', forgetPassword);
router.patch('/resetPassword', resetPassword);
router.patch('/updatePassword', updatePassword);
router.delete('/deleteAccount', deleteAccount);
router.get('/getUser/:id', getUser);
router.patch('/updateProfile',  updateProfile);
router.post('/addanim',addanim);
router.patch('/editeanimal',editeanimal);
router.delete('/removeanimal',removeanimal);
module.exports = router;